SELECT * FROM Exercise;
SELECT * FROM Client;
SELECT * FROM Client WHERE City='Metairie';
SELECT * FROM Client WHERE ClientID='818u7faf-7b4b-48a2-bf12-7a26c92de20c';
SELECT * FROM Goal;
SELECT name,levelid FROM Workout;
SELECT name,levelid,notes FROM Workout WHERE levelid=2;
SELECT firstname,lastname,city FROM Client WHERE city IN ('Metairie','Kenner','Gretna');
SELECT firstname,lastname,birthdate FROM Client WHERE birthdate LIKE '198%';
SELECT firstname,lastname,birthdate FROM Client WHERE birthdate BETWEEN '1980-01-01' AND '1989-12-31' ;
SELECT * FROM Login WHERE EmailAddress LIKE '%.gov';
SELECT * FROM Login WHERE EmailAddress NOT LIKE '%.com';
SELECT firstname,lastname FROM Client WHERE BirthDate is NULL;
SELECT name FROM ExerciseCategory WHERE ParentCategoryID is NOT NULL;
SELECT name,notes FROM Workout WHERE levelid=3 AND notes LIKE '%you%';
SELECT firstname,lastname,city FROM client WHERE (lastname LIKE 'L%' OR lastname LIKE 'M%' OR lastname LIKE 'N%') AND city='LaPlace';
SELECT invoiceid,description,price,quantity,servicedate, price*quantity AS line_item_total FROM InvoiceLineItem WHERE price*quantity BETWEEN 15 AND 25;
SELECT EmailAddress FROM Login WHERE clientid=(SELECT clientid FROM client WHERE firstname='Estrella' and lastname='Bazely');
SELECT name FROM Goal WHERE Goalid IN (SELECT Goalid FROM WorkoutGoal WHERE Workoutid=(SELECT workoutid FROM workout WHERE name='This is Parkour'));
